package com.example.SearchService.model;

/**
 * SUBJECT TO CHANGE, THIS WAS JUST AN IDEA
 */
public enum Category {
    VEHICLES,
    PROPERTY_RENTALS,
    PROPERTIES_FOR_SALE,
    JOBS,
    HOME_GARDEN,
    ELECTRONICS,
    FASHION_ACCESSORIES,
    FAMILY_BABY_KIDS,
    SPORTS_OUTDOORS,
    HOBBIES_GAMES,
    PETS,
    MUSIC_FILMS_BOOKS,
    SERVICES,
    OTHER
}
